import * as Images from "../../common/constants/db-images";
import { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "jardim-svg",
    coverPhoto: Images.JARDIM_SVG_IMAGE_5,
    tags: [
      "residencial",
      "praia",
      "garopaba",
      "maresia",
      "privacidade",
      "piscina",
    ],
    images: [
      Images.JARDIM_SVG_IMAGE_1,
      Images.JARDIM_SVG_IMAGE_2,
      Images.JARDIM_SVG_IMAGE_3,
      Images.JARDIM_SVG_IMAGE_4,
      Images.JARDIM_SVG_IMAGE_5,
      Images.JARDIM_SVG_IMAGE_6,
      Images.JARDIM_SVG_IMAGE_7,
    ],
  },
  {
    slug: "jardim-atj",
    coverPhoto: Images.JARDIM_ATJ_IMAGE_8,
    tags: [
      "residencial",
      "praia",
      "garopaba",
      "praiadosilveira",
      "maresia",
      "orgânico",
      "piscina",
      "visual",
      "morro",
      "natureza",
    ],
    images: [
      Images.JARDIM_ATJ_IMAGE_1,
      Images.JARDIM_ATJ_IMAGE_2,
      Images.JARDIM_ATJ_IMAGE_3,
      Images.JARDIM_ATJ_IMAGE_4,
      Images.JARDIM_ATJ_IMAGE_5,
      Images.JARDIM_ATJ_IMAGE_6,
      Images.JARDIM_ATJ_IMAGE_7,
      Images.JARDIM_ATJ_IMAGE_8,
    ],
  },
  {
    slug: "jardim-ltx",
    coverPhoto: Images.JARDIM_LTX_IMAGE_8,
    tags: [
      "residencial",
      "piscina",
      "xangrila",
      "retilinio",
      "fonte",
      "folhosas",
    ],
    images: [
      Images.JARDIM_LTX_IMAGE_1,
      Images.JARDIM_LTX_IMAGE_2,
      Images.JARDIM_LTX_IMAGE_3,
      Images.JARDIM_LTX_IMAGE_4,
      Images.JARDIM_LTX_IMAGE_5,
      Images.JARDIM_LTX_IMAGE_6,
      Images.JARDIM_LTX_IMAGE_7,
      Images.JARDIM_LTX_IMAGE_8,
      Images.JARDIM_LTX_IMAGE_9,
      Images.JARDIM_LTX_IMAGE_10,
      Images.JARDIM_LTX_IMAGE_11,
    ],
  },
  {
    slug: "jardim-malu",
    coverPhoto: Images.JARDIM_MALU_IMAGE_2,
    tags: ["residencial", "jardim", "internacional"],
    images: [
      Images.JARDIM_MALU_IMAGE_1,
      Images.JARDIM_MALU_IMAGE_2,
      Images.JARDIM_MALU_IMAGE_3,
      Images.JARDIM_MALU_IMAGE_4,
      Images.JARDIM_MALU_IMAGE_5,
      Images.JARDIM_MALU_IMAGE_6,
    ],
  },
  {
    slug: "colegio-farroupilha",
    coverPhoto: Images.COLEGIO_FARROUPILHA_IMAGE_1,
    tags: [
      "institucional",
      "colégio",
      "urbanismo",
      "portoalegre",
      "orgânico",
      "público",
      "calçada",
      "passeio",
    ],
    images: [
      Images.COLEGIO_FARROUPILHA_IMAGE_1,
      Images.COLEGIO_FARROUPILHA_IMAGE_2,
      Images.COLEGIO_FARROUPILHA_IMAGE_3,
      Images.COLEGIO_FARROUPILHA_IMAGE_4,
      Images.COLEGIO_FARROUPILHA_IMAGE_5,
      Images.COLEGIO_FARROUPILHA_IMAGE_6,
      Images.COLEGIO_FARROUPILHA_IMAGE_7,
    ],
  },
  {
    slug: "varanda-fek",
    coverPhoto: Images.VARANDA_FEK_IMAGE_1,
    tags: [
      "varanda",
      "portoalegre",
      "orgânico",
      "marmore",
      "vasos",
      "mobiliario",
    ],
    images: [
      Images.VARANDA_FEK_IMAGE_1,
      Images.VARANDA_FEK_IMAGE_2,
      Images.VARANDA_FEK_IMAGE_3,
      Images.VARANDA_FEK_IMAGE_4,
    ],
  },
  {
    slug: "rampa",
    coverPhoto: Images.RAMPA_IMAGE_3,
    tags: ["institucional", "pelotas", "público", "escada", "rampa", "capim"],
    images: [
      Images.RAMPA_IMAGE_1,
      Images.RAMPA_IMAGE_2,
      Images.RAMPA_IMAGE_3,
      Images.RAMPA_IMAGE_4,
      Images.RAMPA_IMAGE_5,
      Images.RAMPA_IMAGE_6,
      Images.RAMPA_IMAGE_7,
    ],
  },
  {
    slug: "shopping-iguatemi",
    coverPhoto: Images.SHOPPING_IGUATEMI_IMAGE_4,
    tags: [
      "shopping",
      "institucional",
      "iguatemi",
      "portoalegre",
      "vasos",
      "mobiliario",
      "público",
    ],
    images: [
      Images.SHOPPING_IGUATEMI_IMAGE_1,
      Images.SHOPPING_IGUATEMI_IMAGE_2,
      Images.SHOPPING_IGUATEMI_IMAGE_3,
      Images.SHOPPING_IGUATEMI_IMAGE_4,
      Images.SHOPPING_IGUATEMI_IMAGE_5,
    ],
  },
  {
    slug: "jardim-flv",
    coverPhoto: Images.JARDIM_FLV_IMAGE_13,
    tags: [
      "riodejaneiro",
      "cristo",
      "tropical",
      "folhosas",
      "bernardes",
      "residencial",
    ],
    images: [
      Images.JARDIM_FLV_IMAGE_1,
      Images.JARDIM_FLV_IMAGE_2,
      Images.JARDIM_FLV_IMAGE_3,
      Images.JARDIM_FLV_IMAGE_4,
      Images.JARDIM_FLV_IMAGE_5,
      Images.JARDIM_FLV_IMAGE_6,
      Images.JARDIM_FLV_IMAGE_7,
      Images.JARDIM_FLV_IMAGE_8,
      Images.JARDIM_FLV_IMAGE_9,
      Images.JARDIM_FLV_IMAGE_10,
      Images.JARDIM_FLV_IMAGE_11,
      Images.JARDIM_FLV_IMAGE_12,
      Images.JARDIM_FLV_IMAGE_13,
      Images.JARDIM_FLV_IMAGE_14,
    ],
  },
  {
    slug: "rua-mista-legano",
    coverPhoto: Images.RUA_MISTA_LEGANO_IMAGE_1,
    tags: [
      "institucional",
      "ruamista",
      "passeio",
      "público",
      "urbanismo",
      "novasantarita",
      "mobiliario",
      "basalto",
      "condominio",
    ],
    images: [
      Images.RUA_MISTA_LEGANO_IMAGE_1,
      Images.RUA_MISTA_LEGANO_IMAGE_2,
      Images.RUA_MISTA_LEGANO_IMAGE_3,
      Images.RUA_MISTA_LEGANO_IMAGE_4,
      Images.RUA_MISTA_LEGANO_IMAGE_5,
      Images.RUA_MISTA_LEGANO_IMAGE_6,
      Images.RUA_MISTA_LEGANO_IMAGE_7,
      Images.RUA_MISTA_LEGANO_IMAGE_8,
      Images.RUA_MISTA_LEGANO_IMAGE_9,
      Images.RUA_MISTA_LEGANO_IMAGE_10,
    ],
  },
  {
    slug: "surfland",
    coverPhoto: Images.SURFLAND_IMAGE_2,
    tags: ["praia", "resort", "surf", "parque", "garopaba", "sc"],
    images: [
      Images.SURFLAND_IMAGE_1,
      Images.SURFLAND_IMAGE_2,
      Images.SURFLAND_IMAGE_3,
      Images.SURFLAND_IMAGE_4,
      Images.SURFLAND_IMAGE_5,
      Images.SURFLAND_IMAGE_6,
      Images.SURFLAND_IMAGE_7,
      Images.SURFLAND_IMAGE_8,
      Images.SURFLAND_IMAGE_9,
      Images.SURFLAND_IMAGE_10,
      Images.SURFLAND_IMAGE_11,
      Images.SURFLAND_IMAGE_12,
      Images.SURFLAND_IMAGE_13,
      Images.SURFLAND_IMAGE_14,
    ],
  },
  {
    slug: "unisinos",
    coverPhoto: Images.UNISINOS_IMAGE_1,
    tags: ["institucional", "universidade", "publico", "portoalegre"],
    images: [
      Images.UNISINOS_IMAGE_1,
      Images.UNISINOS_IMAGE_2,
      Images.UNISINOS_IMAGE_3,
      Images.UNISINOS_IMAGE_4,
      Images.UNISINOS_IMAGE_5,
      Images.UNISINOS_IMAGE_6,
      Images.UNISINOS_IMAGE_7,
      Images.UNISINOS_IMAGE_8,
      Images.UNISINOS_IMAGE_9,
      Images.UNISINOS_IMAGE_10,
      Images.UNISINOS_IMAGE_11,
      Images.UNISINOS_IMAGE_12,
      Images.UNISINOS_IMAGE_13,
      Images.UNISINOS_IMAGE_14,
      Images.UNISINOS_IMAGE_15,
      Images.UNISINOS_IMAGE_16,
      Images.UNISINOS_IMAGE_17,
    ],
  },
  {
    slug: "edificio-paix",
    coverPhoto: Images.EDIFICIO_PAIX_IMAGE_3,
    tags: ["edificio", "uruguai", "labarra"],
    images: [
      Images.EDIFICIO_PAIX_IMAGE_1,
      Images.EDIFICIO_PAIX_IMAGE_2,
      Images.EDIFICIO_PAIX_IMAGE_3,
      Images.EDIFICIO_PAIX_IMAGE_4,
      Images.EDIFICIO_PAIX_IMAGE_5,
      Images.EDIFICIO_PAIX_IMAGE_6,
      Images.EDIFICIO_PAIX_IMAGE_7,
    ],
  },
  {
    slug: "edificio-iguacu",
    coverPhoto: Images.EDIFICIO_IGUACU_IMAGE_7,
    tags: ["edificio", "portoalegre"],
    images: [
      Images.EDIFICIO_IGUACU_IMAGE_1,
      Images.EDIFICIO_IGUACU_IMAGE_2,
      Images.EDIFICIO_IGUACU_IMAGE_3,
      Images.EDIFICIO_IGUACU_IMAGE_4,
      Images.EDIFICIO_IGUACU_IMAGE_5,
      Images.EDIFICIO_IGUACU_IMAGE_6,
      Images.EDIFICIO_IGUACU_IMAGE_7,
      Images.EDIFICIO_IGUACU_IMAGE_8,
    ],
  },
];
