import {
  COLEGIO_FARROUPILHA_IMAGE_1,
  COLEGIO_FARROUPILHA_IMAGE_2,
  COLEGIO_FARROUPILHA_IMAGE_3,
  COLEGIO_FARROUPILHA_IMAGE_4,
  COLEGIO_FARROUPILHA_IMAGE_5,
  COLEGIO_FARROUPILHA_IMAGE_6,
  COLEGIO_FARROUPILHA_IMAGE_7,
  JARDIM_ATJ_IMAGE_1,
  JARDIM_ATJ_IMAGE_2,
  JARDIM_ATJ_IMAGE_3,
  JARDIM_ATJ_IMAGE_4,
  JARDIM_ATJ_IMAGE_5,
  JARDIM_ATJ_IMAGE_6,
  JARDIM_ATJ_IMAGE_7,
  JARDIM_ATJ_IMAGE_8,
  JARDIM_LTX_IMAGE_1,
  JARDIM_LTX_IMAGE_2,
  JARDIM_LTX_IMAGE_3,
  JARDIM_LTX_IMAGE_4,
  JARDIM_LTX_IMAGE_5,
  JARDIM_LTX_IMAGE_6,
  JARDIM_LTX_IMAGE_7,
  JARDIM_LTX_IMAGE_8,
  JARDIM_LTX_IMAGE_9,
  JARDIM_LTX_IMAGE_10,
  JARDIM_LTX_IMAGE_11,
  JARDIM_MALU_IMAGE_1,
  JARDIM_MALU_IMAGE_2,
  JARDIM_MALU_IMAGE_3,
  JARDIM_MALU_IMAGE_4,
  JARDIM_MALU_IMAGE_5,
  JARDIM_MALU_IMAGE_6,
  JARDIM_SVG_IMAGE_1,
  JARDIM_SVG_IMAGE_2,
  JARDIM_SVG_IMAGE_3,
  JARDIM_SVG_IMAGE_4,
  JARDIM_SVG_IMAGE_5,
  JARDIM_SVG_IMAGE_6,
  JARDIM_SVG_IMAGE_7,
  RAMPA_IMAGE_1,
  RAMPA_IMAGE_2,
  RAMPA_IMAGE_3,
  RAMPA_IMAGE_4,
  RAMPA_IMAGE_5,
  RAMPA_IMAGE_6,
  RAMPA_IMAGE_7,
  SHOPPING_IGUATEMI_IMAGE_1,
  SHOPPING_IGUATEMI_IMAGE_2,
  SHOPPING_IGUATEMI_IMAGE_3,
  SHOPPING_IGUATEMI_IMAGE_4,
  SHOPPING_IGUATEMI_IMAGE_5,
  VARANDA_FEK_IMAGE_1,
  VARANDA_FEK_IMAGE_2,
  VARANDA_FEK_IMAGE_3,
  VARANDA_FEK_IMAGE_4,
} from "../../common/constants/db-images";
import { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "jardim-svg",
    coverPhoto: JARDIM_SVG_IMAGE_5,
    tags: ["residencial", "jardim", "praia", "piscina"],
    images: [
      JARDIM_SVG_IMAGE_1,
      JARDIM_SVG_IMAGE_2,
      JARDIM_SVG_IMAGE_3,
      JARDIM_SVG_IMAGE_4,
      JARDIM_SVG_IMAGE_5,
      JARDIM_SVG_IMAGE_6,
      JARDIM_SVG_IMAGE_7,
    ],
  },
  {
    slug: "jardim-atj",
    coverPhoto: JARDIM_ATJ_IMAGE_8,
    tags: ["residencial", "jardim", "praia", "piscina", "bosque"],
    images: [
      JARDIM_ATJ_IMAGE_1,
      JARDIM_ATJ_IMAGE_2,
      JARDIM_ATJ_IMAGE_3,
      JARDIM_ATJ_IMAGE_4,
      JARDIM_ATJ_IMAGE_5,
      JARDIM_ATJ_IMAGE_6,
      JARDIM_ATJ_IMAGE_7,
      JARDIM_ATJ_IMAGE_8,
    ],
  },
  {
    slug: "jardim-ltx",
    coverPhoto: JARDIM_LTX_IMAGE_8,
    tags: ["residencial", "jardim", "praia", "piscina", "revitalização"],
    images: [
      JARDIM_LTX_IMAGE_1,
      JARDIM_LTX_IMAGE_2,
      JARDIM_LTX_IMAGE_3,
      JARDIM_LTX_IMAGE_4,
      JARDIM_LTX_IMAGE_5,
      JARDIM_LTX_IMAGE_6,
      JARDIM_LTX_IMAGE_7,
      JARDIM_LTX_IMAGE_8,
      JARDIM_LTX_IMAGE_9,
      JARDIM_LTX_IMAGE_10,
      JARDIM_LTX_IMAGE_11,
    ],
  },
  {
    slug: "jardim-malu",
    coverPhoto: JARDIM_MALU_IMAGE_2,
    tags: ["residencial", "jardim", "internacional"],
    images: [
      JARDIM_MALU_IMAGE_1,
      JARDIM_MALU_IMAGE_2,
      JARDIM_MALU_IMAGE_3,
      JARDIM_MALU_IMAGE_4,
      JARDIM_MALU_IMAGE_5,
      JARDIM_MALU_IMAGE_6,
    ],
  },
  {
    slug: "colegio-farroupilha",
    coverPhoto: COLEGIO_FARROUPILHA_IMAGE_1,
    tags: ["institucional", "urbano", "escola", "público"],
    images: [
      COLEGIO_FARROUPILHA_IMAGE_1,
      COLEGIO_FARROUPILHA_IMAGE_2,
      COLEGIO_FARROUPILHA_IMAGE_3,
      COLEGIO_FARROUPILHA_IMAGE_4,
      COLEGIO_FARROUPILHA_IMAGE_5,
      COLEGIO_FARROUPILHA_IMAGE_6,
      COLEGIO_FARROUPILHA_IMAGE_7,
    ],
  },
  {
    slug: "varanda-fek",
    coverPhoto: VARANDA_FEK_IMAGE_1,
    tags: ["residencial", "varanda", "urbano", "terraço"],
    images: [
      VARANDA_FEK_IMAGE_1,
      VARANDA_FEK_IMAGE_2,
      VARANDA_FEK_IMAGE_3,
      VARANDA_FEK_IMAGE_4,
    ],
  },
  {
    slug: "rampa",
    coverPhoto: RAMPA_IMAGE_3,
    tags: ["público", "terraço", "urbano", "cobertura"],
    images: [
      RAMPA_IMAGE_1,
      RAMPA_IMAGE_2,
      RAMPA_IMAGE_3,
      RAMPA_IMAGE_4,
      RAMPA_IMAGE_5,
      RAMPA_IMAGE_6,
      RAMPA_IMAGE_7,
    ],
  },
  {
    slug: "shopping-iguatemi",
    coverPhoto: SHOPPING_IGUATEMI_IMAGE_4,
    tags: ["comercial", "urbano", "público"],
    images: [
      SHOPPING_IGUATEMI_IMAGE_1,
      SHOPPING_IGUATEMI_IMAGE_2,
      SHOPPING_IGUATEMI_IMAGE_3,
      SHOPPING_IGUATEMI_IMAGE_4,
      SHOPPING_IGUATEMI_IMAGE_5,
    ],
  },
];
