import * as Images from "../../common/constants/db-images";
import { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "jardim-svg",
    coverPhoto: Images.JARDIM_SVG_IMAGE_3,
    tags: ["residencial", "praia", "garopaba", "piscina"],
    images: [
      Images.JARDIM_SVG_IMAGE_1,
      Images.JARDIM_SVG_IMAGE_2,
      Images.JARDIM_SVG_IMAGE_3,
      Images.JARDIM_SVG_IMAGE_4,
      Images.JARDIM_SVG_IMAGE_5,
      Images.JARDIM_SVG_IMAGE_6,
      Images.JARDIM_SVG_IMAGE_7,
    ],
    conclusionDate: "2023",
  },
  {
    slug: "jardim-atj",
    coverPhoto: Images.JARDIM_ATJ_IMAGE_6,
    tags: ["residencial", "praia", "garopaba", "piscina", "natureza"],
    images: [
      Images.JARDIM_ATJ_IMAGE_1,
      Images.JARDIM_ATJ_IMAGE_2,
      Images.JARDIM_ATJ_IMAGE_3,
      Images.JARDIM_ATJ_IMAGE_4,
      Images.JARDIM_ATJ_IMAGE_5,
      Images.JARDIM_ATJ_IMAGE_6,
      Images.JARDIM_ATJ_IMAGE_7,
      Images.JARDIM_ATJ_IMAGE_8,
    ],
    conclusionDate: "2018",
  },
  {
    slug: "jardim-ltx",
    coverPhoto: Images.JARDIM_LTX_IMAGE_2,
    tags: ["residencial", "piscina", "xangrila"],
    images: [
      Images.JARDIM_LTX_IMAGE_1,
      Images.JARDIM_LTX_IMAGE_2,
      Images.JARDIM_LTX_IMAGE_3,
      Images.JARDIM_LTX_IMAGE_4,
      Images.JARDIM_LTX_IMAGE_5,
      Images.JARDIM_LTX_IMAGE_6,
      Images.JARDIM_LTX_IMAGE_7,
      Images.JARDIM_LTX_IMAGE_8,
      Images.JARDIM_LTX_IMAGE_9,
      Images.JARDIM_LTX_IMAGE_10,
      Images.JARDIM_LTX_IMAGE_11,
    ],
    conclusionDate: "2018",
  },
  {
    slug: "jardim-malu",
    coverPhoto: Images.JARDIM_MALU_IMAGE_1,
    tags: ["residencial", "jardim", "internacional"],
    images: [
      Images.JARDIM_MALU_IMAGE_1,
      Images.JARDIM_MALU_IMAGE_2,
      Images.JARDIM_MALU_IMAGE_3,
      Images.JARDIM_MALU_IMAGE_4,
      Images.JARDIM_MALU_IMAGE_5,
      Images.JARDIM_MALU_IMAGE_6,
    ],
    conclusionDate: "2020",
  },
  {
    slug: "colegio-farroupilha",
    coverPhoto: Images.COLEGIO_FARROUPILHA_IMAGE_4,
    tags: ["institucional", "colégio", "urbanismo", "portoalegre"],
    images: [
      Images.COLEGIO_FARROUPILHA_IMAGE_1,
      Images.COLEGIO_FARROUPILHA_IMAGE_2,
      Images.COLEGIO_FARROUPILHA_IMAGE_3,
      Images.COLEGIO_FARROUPILHA_IMAGE_4,
      Images.COLEGIO_FARROUPILHA_IMAGE_5,
      Images.COLEGIO_FARROUPILHA_IMAGE_6,
      Images.COLEGIO_FARROUPILHA_IMAGE_7,
    ],
    conclusionDate: "2025",
  },
  {
    slug: "varanda-fek",
    coverPhoto: Images.VARANDA_FEK_IMAGE_1,
    tags: ["varanda", "portoalegre"],
    images: [
      Images.VARANDA_FEK_IMAGE_1,
      Images.VARANDA_FEK_IMAGE_2,
      Images.VARANDA_FEK_IMAGE_3,
      Images.VARANDA_FEK_IMAGE_4,
    ],
    conclusionDate: "2024",
  },
  {
    slug: "rampa",
    coverPhoto: Images.RAMPA_IMAGE_4,
    tags: ["institucional", "pelotas", "público"],
    images: [
      Images.RAMPA_IMAGE_1,
      Images.RAMPA_IMAGE_2,
      Images.RAMPA_IMAGE_3,
      Images.RAMPA_IMAGE_4,
      Images.RAMPA_IMAGE_5,
      Images.RAMPA_IMAGE_6,
      Images.RAMPA_IMAGE_7,
    ],
    conclusionDate: "2024",
  },
  {
    slug: "shopping-iguatemi",
    coverPhoto: Images.SHOPPING_IGUATEMI_IMAGE_3,
    tags: ["shopping", "institucional", "portoalegre"],
    images: [
      Images.SHOPPING_IGUATEMI_IMAGE_1,
      Images.SHOPPING_IGUATEMI_IMAGE_2,
      Images.SHOPPING_IGUATEMI_IMAGE_3,
      Images.SHOPPING_IGUATEMI_IMAGE_4,
      Images.SHOPPING_IGUATEMI_IMAGE_5,
    ],
    conclusionDate: "2017",
  },
  {
    slug: "jardim-flv",
    coverPhoto: Images.JARDIM_FLV_IMAGE_9,
    tags: ["riodejaneiro", "tropical", "residencial"],
    images: [
      Images.JARDIM_FLV_IMAGE_1,
      Images.JARDIM_FLV_IMAGE_2,
      Images.JARDIM_FLV_IMAGE_3,
      Images.JARDIM_FLV_IMAGE_4,
      Images.JARDIM_FLV_IMAGE_5,
      Images.JARDIM_FLV_IMAGE_6,
      Images.JARDIM_FLV_IMAGE_7,
      Images.JARDIM_FLV_IMAGE_8,
      Images.JARDIM_FLV_IMAGE_9,
      Images.JARDIM_FLV_IMAGE_10,
      Images.JARDIM_FLV_IMAGE_11,
      Images.JARDIM_FLV_IMAGE_12,
      Images.JARDIM_FLV_IMAGE_13,
    ],
    conclusionDate: "2023",
  },
  {
    slug: "rua-mista-legano",
    coverPhoto: Images.RUA_MISTA_LEGANO_IMAGE_2,
    tags: ["institucional", "público", "urbanismo", "novasantarita"],
    images: [
      Images.RUA_MISTA_LEGANO_IMAGE_1,
      Images.RUA_MISTA_LEGANO_IMAGE_2,
      Images.RUA_MISTA_LEGANO_IMAGE_3,
      Images.RUA_MISTA_LEGANO_IMAGE_4,
      Images.RUA_MISTA_LEGANO_IMAGE_5,
      Images.RUA_MISTA_LEGANO_IMAGE_6,
      Images.RUA_MISTA_LEGANO_IMAGE_7,
      Images.RUA_MISTA_LEGANO_IMAGE_8,
      Images.RUA_MISTA_LEGANO_IMAGE_9,
      Images.RUA_MISTA_LEGANO_IMAGE_10,
    ],
    conclusionDate: "2020",
  },
  {
    slug: "surfland",
    coverPhoto: Images.SURFLAND_IMAGE_4,
    tags: ["resort", "surf", "parque", "garopaba"],
    images: [
      Images.SURFLAND_IMAGE_1,
      Images.SURFLAND_IMAGE_2,
      Images.SURFLAND_IMAGE_3,
      Images.SURFLAND_IMAGE_4,
      Images.SURFLAND_IMAGE_5,
      Images.SURFLAND_IMAGE_6,
      Images.SURFLAND_IMAGE_7,
      Images.SURFLAND_IMAGE_8,
      Images.SURFLAND_IMAGE_9,
      Images.SURFLAND_IMAGE_10,
      Images.SURFLAND_IMAGE_11,
      Images.SURFLAND_IMAGE_12,
      Images.SURFLAND_IMAGE_13,
      Images.SURFLAND_IMAGE_14,
    ],
    conclusionDate: "2023",
  },
  {
    slug: "unisinos",
    coverPhoto: Images.UNISINOS_IMAGE_1,
    tags: ["institucional", "universidade", "publico", "portoalegre"],
    images: [
      Images.UNISINOS_IMAGE_1,
      Images.UNISINOS_IMAGE_2,
      Images.UNISINOS_IMAGE_3,
      Images.UNISINOS_IMAGE_4,
      Images.UNISINOS_IMAGE_5,
      Images.UNISINOS_IMAGE_6,
      Images.UNISINOS_IMAGE_7,
      Images.UNISINOS_IMAGE_8,
      Images.UNISINOS_IMAGE_9,
      Images.UNISINOS_IMAGE_10,
      Images.UNISINOS_IMAGE_11,
      Images.UNISINOS_IMAGE_12,
      Images.UNISINOS_IMAGE_13,
      Images.UNISINOS_IMAGE_14,
      Images.UNISINOS_IMAGE_15,
      Images.UNISINOS_IMAGE_16,
      Images.UNISINOS_IMAGE_17,
    ],
    conclusionDate: "2017",
  },
  {
    slug: "edificio-paix",
    coverPhoto: Images.EDIFICIO_PAIX_IMAGE_3,
    tags: ["edificio", "uruguai", "labarra"],
    images: [
      Images.EDIFICIO_PAIX_IMAGE_1,
      Images.EDIFICIO_PAIX_IMAGE_2,
      Images.EDIFICIO_PAIX_IMAGE_3,
      Images.EDIFICIO_PAIX_IMAGE_4,
      Images.EDIFICIO_PAIX_IMAGE_5,
      Images.EDIFICIO_PAIX_IMAGE_6,
      Images.EDIFICIO_PAIX_IMAGE_7,
    ],
    conclusionDate: "2020",
  },
  {
    slug: "edificio-iguacu",
    coverPhoto: Images.EDIFICIO_IGUACU_IMAGE_4,
    tags: ["edificio", "portoalegre"],
    images: [
      Images.EDIFICIO_IGUACU_IMAGE_1,
      Images.EDIFICIO_IGUACU_IMAGE_2,
      Images.EDIFICIO_IGUACU_IMAGE_3,
      Images.EDIFICIO_IGUACU_IMAGE_4,
      Images.EDIFICIO_IGUACU_IMAGE_5,
      Images.EDIFICIO_IGUACU_IMAGE_6,
      Images.EDIFICIO_IGUACU_IMAGE_7,
      Images.EDIFICIO_IGUACU_IMAGE_8,
    ],
    conclusionDate: "2020",
  },
  {
    slug: "jardim-lmp",
    coverPhoto: Images.JARDIM_LMP_IMAGE_5,
    tags: ["uruguai", "residencial"],
    images: [
      Images.JARDIM_LMP_IMAGE_1,
      Images.JARDIM_LMP_IMAGE_2,
      Images.JARDIM_LMP_IMAGE_3,
      Images.JARDIM_LMP_IMAGE_4,
      Images.JARDIM_LMP_IMAGE_5,
    ],
    conclusionDate: "2023",
  },
  {
    slug: "jardim-ssg",
    coverPhoto: Images.JARDIM_SSG_IMAGE_5,
    tags: ["garopaba", "residencial", "praia"],
    images: [
      Images.JARDIM_SSG_IMAGE_1,
      Images.JARDIM_SSG_IMAGE_2,
      Images.JARDIM_SSG_IMAGE_3,
      Images.JARDIM_SSG_IMAGE_4,
      Images.JARDIM_SSG_IMAGE_5,
      Images.JARDIM_SSG_IMAGE_6,
      Images.JARDIM_SSG_IMAGE_7,
      Images.JARDIM_SSG_IMAGE_8,
      Images.JARDIM_SSG_IMAGE_9,
    ],
    conclusionDate: "2021",
  },
  {
    slug: "jardim-adg",
    coverPhoto: Images.JARDIM_ADG_IMAGE_7,
    tags: ["garopaba", "residencial", "praia"],
    images: [
      Images.JARDIM_ADG_IMAGE_1,
      Images.JARDIM_ADG_IMAGE_2,
      Images.JARDIM_ADG_IMAGE_3,
      Images.JARDIM_ADG_IMAGE_4,
      Images.JARDIM_ADG_IMAGE_5,
      Images.JARDIM_ADG_IMAGE_6,
      Images.JARDIM_ADG_IMAGE_7,
    ],
    conclusionDate: "2012",
  },
  {
    slug: "prado-bairro-cidade",
    coverPhoto: Images.PRADO_BAIRRO_CIDADE_IMAGE_3,
    tags: ["condominio", "gravatai", "urbanismo", "bairro"],
    images: [
      Images.PRADO_BAIRRO_CIDADE_IMAGE_1,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_2,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_3,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_4,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_5,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_6,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_7,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_8,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_9,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_10,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_11,
      Images.PRADO_BAIRRO_CIDADE_IMAGE_12,
    ],
    conclusionDate: "2016",
  },
];
