const IMAGE_DB_URL = "https://8vncue4ikz.ufs.sh/f/";

// PROJECTS IMAGES

const JARDIM_MALU_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1t6X41gVJHrBf1Iixg0onmjb3NqTLCud8GyRXF`;
const JARDIM_MALU_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tZ0SrsQbP65mieWuXK4qrMHwjJGF7EPzhkc2b`;
const JARDIM_MALU_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tojfmeEWRfOSyP1UZ3t2b5QCGpqujFBJci4g6`;
const JARDIM_MALU_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tyzYMPOqhS65cD3qFOiuHBU8fso9xvjgeRYI2`;
const JARDIM_MALU_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1t8imWsjKriLRAZFwTpz3O50xB8UeMDVu2H7no`;
const JARDIM_MALU_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1taKfHeWUFvRYTBjCi9uJ1f0Z4pHlhmrdN2I8X`;

const JARDIM_SVG_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tqktFsiN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;
const JARDIM_SVG_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tvyWWVS3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
const JARDIM_SVG_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tIxFUxfsuwTdvY5Ftin0NGsgakmOqQUDW8HjE`;
const JARDIM_SVG_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1toRxeUBgWRfOSyP1UZ3t2b5QCGpqujFBJci4g`;
const JARDIM_SVG_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tFS6AkMEIihnVXLpkHKEeaZft6SRuWB3C2zyG`;
const JARDIM_SVG_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tlBjAWsCzNGSVlAot962QihrTvJHPC7LMXmyR`;
const JARDIM_SVG_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tKT4PssYrlqWrTSoENn9ZHw4vbRJAa2XMD37C`;

const JARDIM_LTX_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tRw3k3rhwjI1lGQ2HVNdCso95v3DrYuEK6SnZ`;
const JARDIM_LTX_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tKlopjerlqWrTSoENn9ZHw4vbRJAa2XMD37Ci`;
const JARDIM_LTX_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tvawf1Y3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
const JARDIM_LTX_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tvf8w0R3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
const JARDIM_LTX_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tY3Qjlz6RDs9QZthiVKkHBEud1M7OP0YgwnrG`;
const JARDIM_LTX_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tQHP9FD7fSBlxuFIdT5gvNqrHLafKhcjbozYm`;
const JARDIM_LTX_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tXiAvgNFQHW7J1hFdwA0ovBOyS2fZRb5Cm6Iu`;
const JARDIM_LTX_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tIV7ZzhuwTdvY5Ftin0NGsgakmOqQUDW8HjEy`;
const JARDIM_LTX_IMAGE_9 = `${IMAGE_DB_URL}SLdhHfnzGw1t5iHPgS1HvnOVqXwlL9p0RYPFbaUhyKm3BuC2`;
const JARDIM_LTX_IMAGE_10 = `${IMAGE_DB_URL}SLdhHfnzGw1t0q6LT7pcwXGJHeQNFUotsS40AyTWlVm6kIKD`;
const JARDIM_LTX_IMAGE_11 = `${IMAGE_DB_URL}SLdhHfnzGw1tqW1XVdN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;

const JARDIM_ATJ_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tlX6ct31CzNGSVlAot962QihrTvJHPC7LMXmy`;
const JARDIM_ATJ_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tHbQBM2DnvUsCIkWOjYQVHr5mRNqPhzwT83e7`;
const JARDIM_ATJ_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tUjO3YEg7YDmvMJ3yiBXLrTWZwIbpeS0xdU6O`;
const JARDIM_ATJ_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tj4Rzx15RX0q95nZbsGf8YKT47juwgrJvWBxp`;
const JARDIM_ATJ_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tdZegHS0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
const JARDIM_ATJ_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tSERthinzGw1t65WAC0xXDkB2pPFiZmogRlUv`;
const JARDIM_ATJ_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1taRFInDUFvRYTBjCi9uJ1f0Z4pHlhmrdN2I8X`;
const JARDIM_ATJ_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tiFIpwcZKiuqILmkobr2tpAYlQH0DO3MVGcCe`;

const RAMPA_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tfDKbPSMbpPJFLdCzNuMZRoYSfTl2VrDjBK9X`;
const RAMPA_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tV5s1Ik7KPMWpDnwkqXZRYITHBQsg0d4avemC`;
const RAMPA_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1t0gWStZpcwXGJHeQNFUotsS40AyTWlVm6kIKD`;
const RAMPA_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tKuCkIRrlqWrTSoENn9ZHw4vbRJAa2XMD37Ci`;
const RAMPA_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tY5bCLG6RDs9QZthiVKkHBEud1M7OP0YgwnrG`;
const RAMPA_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tdwZfbG0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
const RAMPA_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tl1gGIeCzNGSVlAot962QihrTvJHPC7LMXmyR`;

const COLEGIO_FARROUPILHA_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tnWwUeO6bhoODN3vwsTr4k9jaXWbpYVRZq1dG`;
const COLEGIO_FARROUPILHA_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tuY03L9s7GPavDNO8YWMgeLi05C4QynmdBorT`;
const COLEGIO_FARROUPILHA_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1t9GUOrylQmvUPiYkJjq1sTzN3KCEAX4fdcVhS`;
const COLEGIO_FARROUPILHA_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tqgTxRDN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;
const COLEGIO_FARROUPILHA_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tGAAKvvXbWphgNBTOZ9H27u8eS3UxanyPEIRX`;
const COLEGIO_FARROUPILHA_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tBGS2uqR7jU5CeadrNW86DtMxV24qcOwm0sQl`;
const COLEGIO_FARROUPILHA_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1t9IUaUlQmvUPiYkJjq1sTzN3KCEAX4fdcVhSR`;

const VARANDA_FEK_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1t0qS9qkHpcwXGJHeQNFUotsS40AyTWlVm6kIK`;
const VARANDA_FEK_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tOVFTMy8ybBT8EY1VJWIgusi52z3QUfdlXMZx`;
const VARANDA_FEK_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tbjADm9olkB3s0PKmjYv2d5yOT6S8zGVaepZU`;
const VARANDA_FEK_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tQHODvhgfSBlxuFIdT5gvNqrHLafKhcjbozYm`;

const SHOPPING_IGUATEMI_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tdD3Nu30LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
const SHOPPING_IGUATEMI_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tcggCdJeapNYLxAdOtXqVWm4r2v5JfZcizHRU`;
const SHOPPING_IGUATEMI_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tZnAIG5P65mieWuXK4qrMHwjJGF7EPzhkc2bZ`;
const SHOPPING_IGUATEMI_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tIKkYwCuwTdvY5Ftin0NGsgakmOqQUDW8HjEy`;
const SHOPPING_IGUATEMI_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tRXMIn1hwjI1lGQ2HVNdCso95v3DrYuEK6SnZ`;

export {
  IMAGE_DB_URL,
  JARDIM_MALU_IMAGE_1,
  JARDIM_MALU_IMAGE_2,
  JARDIM_MALU_IMAGE_3,
  JARDIM_MALU_IMAGE_4,
  JARDIM_MALU_IMAGE_5,
  JARDIM_MALU_IMAGE_6,
  JARDIM_SVG_IMAGE_1,
  JARDIM_SVG_IMAGE_2,
  JARDIM_SVG_IMAGE_3,
  JARDIM_SVG_IMAGE_4,
  JARDIM_SVG_IMAGE_5,
  JARDIM_SVG_IMAGE_6,
  JARDIM_SVG_IMAGE_7,
  JARDIM_LTX_IMAGE_1,
  JARDIM_LTX_IMAGE_2,
  JARDIM_LTX_IMAGE_3,
  JARDIM_LTX_IMAGE_4,
  JARDIM_LTX_IMAGE_5,
  JARDIM_LTX_IMAGE_6,
  JARDIM_LTX_IMAGE_7,
  JARDIM_LTX_IMAGE_8,
  JARDIM_LTX_IMAGE_9,
  JARDIM_LTX_IMAGE_10,
  JARDIM_LTX_IMAGE_11,
  JARDIM_ATJ_IMAGE_1,
  JARDIM_ATJ_IMAGE_2,
  JARDIM_ATJ_IMAGE_3,
  JARDIM_ATJ_IMAGE_4,
  JARDIM_ATJ_IMAGE_5,
  JARDIM_ATJ_IMAGE_6,
  JARDIM_ATJ_IMAGE_7,
  JARDIM_ATJ_IMAGE_8,
  RAMPA_IMAGE_1,
  RAMPA_IMAGE_2,
  RAMPA_IMAGE_3,
  RAMPA_IMAGE_4,
  RAMPA_IMAGE_5,
  RAMPA_IMAGE_6,
  RAMPA_IMAGE_7,
  COLEGIO_FARROUPILHA_IMAGE_1,
  COLEGIO_FARROUPILHA_IMAGE_2,
  COLEGIO_FARROUPILHA_IMAGE_3,
  COLEGIO_FARROUPILHA_IMAGE_4,
  COLEGIO_FARROUPILHA_IMAGE_5,
  COLEGIO_FARROUPILHA_IMAGE_6,
  COLEGIO_FARROUPILHA_IMAGE_7,
  VARANDA_FEK_IMAGE_1,
  VARANDA_FEK_IMAGE_2,
  VARANDA_FEK_IMAGE_3,
  VARANDA_FEK_IMAGE_4,
  SHOPPING_IGUATEMI_IMAGE_1,
  SHOPPING_IGUATEMI_IMAGE_2,
  SHOPPING_IGUATEMI_IMAGE_3,
  SHOPPING_IGUATEMI_IMAGE_4,
  SHOPPING_IGUATEMI_IMAGE_5,
};
