export const IMAGE_DB_URL = "https://8vncue4ikz.ufs.sh/f/";

// Placeholder blur minimalista (cinza neutro 10x10px)
export const BLUR_PLACEHOLDER =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAIklEQVR4nGNgGCjw////fwY84OTJk/8Z8AEmHAoHNQwYAABWTxANluX/vgAAAABJRU5ErkJggg==";

// PROJECTS IMAGES

export const JARDIM_MALU_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1t6X41gVJHrBf1Iixg0onmjb3NqTLCud8GyRXF`;
export const JARDIM_MALU_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tZ0SrsQbP65mieWuXK4qrMHwjJGF7EPzhkc2b`;
export const JARDIM_MALU_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tojfmeEWRfOSyP1UZ3t2b5QCGpqujFBJci4g6`;
export const JARDIM_MALU_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tyzYMPOqhS65cD3qFOiuHBU8fso9xvjgeRYI2`;
export const JARDIM_MALU_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1t8imWsjKriLRAZFwTpz3O50xB8UeMDVu2H7no`;
export const JARDIM_MALU_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1taKfHeWUFvRYTBjCi9uJ1f0Z4pHlhmrdN2I8X`;

export const JARDIM_SVG_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tqktFsiN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;
export const JARDIM_SVG_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tvyWWVS3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
export const JARDIM_SVG_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tIxFUxfsuwTdvY5Ftin0NGsgakmOqQUDW8HjE`;
export const JARDIM_SVG_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1toRxeUBgWRfOSyP1UZ3t2b5QCGpqujFBJci4g`;
export const JARDIM_SVG_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tFS6AkMEIihnVXLpkHKEeaZft6SRuWB3C2zyG`;
export const JARDIM_SVG_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tlBjAWsCzNGSVlAot962QihrTvJHPC7LMXmyR`;
export const JARDIM_SVG_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tKT4PssYrlqWrTSoENn9ZHw4vbRJAa2XMD37C`;

export const JARDIM_LTX_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tRw3k3rhwjI1lGQ2HVNdCso95v3DrYuEK6SnZ`;
export const JARDIM_LTX_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tKlopjerlqWrTSoENn9ZHw4vbRJAa2XMD37Ci`;
export const JARDIM_LTX_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tvawf1Y3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
export const JARDIM_LTX_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tvf8w0R3hdR4q3tg0aEroIuGfXTOAjSJNHiP2`;
export const JARDIM_LTX_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tY3Qjlz6RDs9QZthiVKkHBEud1M7OP0YgwnrG`;
export const JARDIM_LTX_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tQHP9FD7fSBlxuFIdT5gvNqrHLafKhcjbozYm`;
export const JARDIM_LTX_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tXiAvgNFQHW7J1hFdwA0ovBOyS2fZRb5Cm6Iu`;
export const JARDIM_LTX_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tIV7ZzhuwTdvY5Ftin0NGsgakmOqQUDW8HjEy`;
export const JARDIM_LTX_IMAGE_9 = `${IMAGE_DB_URL}SLdhHfnzGw1t5iHPgS1HvnOVqXwlL9p0RYPFbaUhyKm3BuC2`;
export const JARDIM_LTX_IMAGE_10 = `${IMAGE_DB_URL}SLdhHfnzGw1t0q6LT7pcwXGJHeQNFUotsS40AyTWlVm6kIKD`;
export const JARDIM_LTX_IMAGE_11 = `${IMAGE_DB_URL}SLdhHfnzGw1tqW1XVdN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;

export const JARDIM_ATJ_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tlX6ct31CzNGSVlAot962QihrTvJHPC7LMXmy`;
export const JARDIM_ATJ_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tHbQBM2DnvUsCIkWOjYQVHr5mRNqPhzwT83e7`;
export const JARDIM_ATJ_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tUjO3YEg7YDmvMJ3yiBXLrTWZwIbpeS0xdU6O`;
export const JARDIM_ATJ_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tj4Rzx15RX0q95nZbsGf8YKT47juwgrJvWBxp`;
export const JARDIM_ATJ_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tdZegHS0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
export const JARDIM_ATJ_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tSERthinzGw1t65WAC0xXDkB2pPFiZmogRlUv`;
export const JARDIM_ATJ_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1taRFInDUFvRYTBjCi9uJ1f0Z4pHlhmrdN2I8X`;
export const JARDIM_ATJ_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tiFIpwcZKiuqILmkobr2tpAYlQH0DO3MVGcCe`;

export const RAMPA_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tfDKbPSMbpPJFLdCzNuMZRoYSfTl2VrDjBK9X`;
export const RAMPA_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tV5s1Ik7KPMWpDnwkqXZRYITHBQsg0d4avemC`;
export const RAMPA_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1t0gWStZpcwXGJHeQNFUotsS40AyTWlVm6kIKD`;
export const RAMPA_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tKuCkIRrlqWrTSoENn9ZHw4vbRJAa2XMD37Ci`;
export const RAMPA_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tY5bCLG6RDs9QZthiVKkHBEud1M7OP0YgwnrG`;
export const RAMPA_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tdwZfbG0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
export const RAMPA_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tl1gGIeCzNGSVlAot962QihrTvJHPC7LMXmyR`;

export const COLEGIO_FARROUPILHA_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tnWwUeO6bhoODN3vwsTr4k9jaXWbpYVRZq1dG`;
export const COLEGIO_FARROUPILHA_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tuY03L9s7GPavDNO8YWMgeLi05C4QynmdBorT`;
export const COLEGIO_FARROUPILHA_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1t9GUOrylQmvUPiYkJjq1sTzN3KCEAX4fdcVhS`;
export const COLEGIO_FARROUPILHA_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tqgTxRDN31OobfHlLu6UnJGPRzj0FmI7xA94Y`;
export const COLEGIO_FARROUPILHA_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tGAAKvvXbWphgNBTOZ9H27u8eS3UxanyPEIRX`;
export const COLEGIO_FARROUPILHA_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tBGS2uqR7jU5CeadrNW86DtMxV24qcOwm0sQl`;
export const COLEGIO_FARROUPILHA_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1t9IUaUlQmvUPiYkJjq1sTzN3KCEAX4fdcVhSR`;

export const VARANDA_FEK_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1t0qS9qkHpcwXGJHeQNFUotsS40AyTWlVm6kIK`;
export const VARANDA_FEK_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tOVFTMy8ybBT8EY1VJWIgusi52z3QUfdlXMZx`;
export const VARANDA_FEK_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tbjADm9olkB3s0PKmjYv2d5yOT6S8zGVaepZU`;
export const VARANDA_FEK_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tQHODvhgfSBlxuFIdT5gvNqrHLafKhcjbozYm`;

export const SHOPPING_IGUATEMI_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tdD3Nu30LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
export const SHOPPING_IGUATEMI_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tcggCdJeapNYLxAdOtXqVWm4r2v5JfZcizHRU`;
export const SHOPPING_IGUATEMI_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tZnAIG5P65mieWuXK4qrMHwjJGF7EPzhkc2bZ`;
export const SHOPPING_IGUATEMI_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tIKkYwCuwTdvY5Ftin0NGsgakmOqQUDW8HjEy`;
export const SHOPPING_IGUATEMI_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tRXMIn1hwjI1lGQ2HVNdCso95v3DrYuEK6SnZ`;

export const JARDIM_FLV_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tAAxHQuj8uyIipwxNraKoYv3A0Cc6mzlt957V`;
export const JARDIM_FLV_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tg3twdbV649lgzqAPc7UsCyZ5RGMj1rS2Bxdn`;
export const JARDIM_FLV_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tbpmqc6olkB3s0PKmjYv2d5yOT6S8zGVaepZU`;
export const JARDIM_FLV_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tRwgL8ZhwjI1lGQ2HVNdCso95v3DrYuEK6SnZ`;
export const JARDIM_FLV_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tdy59LsU0LN2xAXy4o1FuqgPRECTrBK83jebs`;
export const JARDIM_FLV_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1thp0B0QA1cy728WDKZnbzG6apkUNegS0Jwtlo`;
export const JARDIM_FLV_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tdktp2z0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
export const JARDIM_FLV_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tiVO6ooZKiuqILmkobr2tpAYlQH0DO3MVGcCe`;
export const JARDIM_FLV_IMAGE_9 = `${IMAGE_DB_URL}SLdhHfnzGw1tBCC7DQR7jU5CeadrNW86DtMxV24qcOwm0sQl`;
export const JARDIM_FLV_IMAGE_10 = `${IMAGE_DB_URL}SLdhHfnzGw1tA12fDpDj8uyIipwxNraKoYv3A0Cc6mzlt957`;
export const JARDIM_FLV_IMAGE_11 = `${IMAGE_DB_URL}SLdhHfnzGw1tJtcirCQ5dMvDhnHEPw140NQ8FTsI3oGmOuk6`;
export const JARDIM_FLV_IMAGE_12 = `${IMAGE_DB_URL}SLdhHfnzGw1tzL9FG1lw5pzaSolJvN3eILXkZqrGHbfRuW9j`;
export const JARDIM_FLV_IMAGE_13 = `${IMAGE_DB_URL}SLdhHfnzGw1tSoIiW1MnzGw1t65WAC0xXDkB2pPFiZmogRlU`;
export const JARDIM_FLV_IMAGE_14 = `${IMAGE_DB_URL}SLdhHfnzGw1tu41Oois7GPavDNO8YWMgeLi05C4QynmdBorT`;

export const RUA_MISTA_LEGANO_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1tyO7alpqhS65cD3qFOiuHBU8fso9xvjgeRYI2`;
export const RUA_MISTA_LEGANO_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tdJlETX0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
export const RUA_MISTA_LEGANO_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tFaLzTMEIihnVXLpkHKEeaZft6SRuWB3C2zyG`;
export const RUA_MISTA_LEGANO_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tNbBmVjiSWgCRr6GsmVuElS3tfOXiBeUJDZhc`;
export const RUA_MISTA_LEGANO_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tDK0YaaVOhP8MTvyt062CZeFzOGcXU9SAwrHu`;
export const RUA_MISTA_LEGANO_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tNW3xmCSWgCRr6GsmVuElS3tfOXiBeUJDZhcq`;
export const RUA_MISTA_LEGANO_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tDsxn0rOhP8MTvyt062CZeFzOGcXU9SAwrHuE`;
export const RUA_MISTA_LEGANO_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tOcmhNT8ybBT8EY1VJWIgusi52z3QUfdlXMZx`;
export const RUA_MISTA_LEGANO_IMAGE_9 = `${IMAGE_DB_URL}SLdhHfnzGw1tPBeNHcdQRLG8n2hju10ENC7ty6TaAwxUpbDg`;
export const RUA_MISTA_LEGANO_IMAGE_10 = `${IMAGE_DB_URL}SLdhHfnzGw1tjvSlaJ5RX0q95nZbsGf8YKT47juwgrJvWBxp`;

export const SURFLAND_IMAGE_1 = `${IMAGE_DB_URL}SLdhHfnzGw1t7zEBrhYp8vREqOTb3PHeNmfLAtKJwk41oWry`;
export const SURFLAND_IMAGE_2 = `${IMAGE_DB_URL}SLdhHfnzGw1tBonbfjR7jU5CeadrNW86DtMxV24qcOwm0sQl`;
export const SURFLAND_IMAGE_3 = `${IMAGE_DB_URL}SLdhHfnzGw1tOynDiv8ybBT8EY1VJWIgusi52z3QUfdlXMZx`;
export const SURFLAND_IMAGE_4 = `${IMAGE_DB_URL}SLdhHfnzGw1tAVnb4ej8uyIipwxNraKoYv3A0Cc6mzlt957V`;
export const SURFLAND_IMAGE_5 = `${IMAGE_DB_URL}SLdhHfnzGw1tAVnb4ej8uyIipwxNraKoYv3A0Cc6mzlt957V`;
export const SURFLAND_IMAGE_6 = `${IMAGE_DB_URL}SLdhHfnzGw1tshSRgpxPW2mvgD93fJlOsaXuNR8CE1S5czH6`;
export const SURFLAND_IMAGE_7 = `${IMAGE_DB_URL}SLdhHfnzGw1tFaMOFJVEIihnVXLpkHKEeaZft6SRuWB3C2zy`;
export const SURFLAND_IMAGE_8 = `${IMAGE_DB_URL}SLdhHfnzGw1tfPomC9MbpPJFLdCzNuMZRoYSfTl2VrDjBK9X`;
export const SURFLAND_IMAGE_9 = `${IMAGE_DB_URL}SLdhHfnzGw1tfLhyhWMbpPJFLdCzNuMZRoYSfTl2VrDjBK9X`;
export const SURFLAND_IMAGE_10 = `${IMAGE_DB_URL}SLdhHfnzGw1t7uUb6RYp8vREqOTb3PHeNmfLAtKJwk41oWry`;
export const SURFLAND_IMAGE_11 = `${IMAGE_DB_URL}SLdhHfnzGw1tWiXkkzBMPxHDKkSjz75thmvpy0fECoeTQZuB`;
export const SURFLAND_IMAGE_12 = `${IMAGE_DB_URL}SLdhHfnzGw1tQorRsMfSBlxuFIdT5gvNqrHLafKhcjbozYm7`;
export const SURFLAND_IMAGE_13 = `${IMAGE_DB_URL}SLdhHfnzGw1tUwYIxWg7YDmvMJ3yiBXLrTWZwIbpeS0xdU6O`;
export const SURFLAND_IMAGE_14 = `${IMAGE_DB_URL}SLdhHfnzGw1tdLTNQM0LN2xAXy4o1FuqgPRECTrBK83jebsZ`;
